export const coinListArray = {
    "BTC": "BITCOIN",
    "ETH": "ETHEREUM",
    "XRP": "XRP",
    "BCH": "Bitcoin-CASH",
    "EOS": "EOS",
    "XLM": "STELLAR",
    "LTC": "LITECOIN",
    "USDT": "TETHER",
    "ADA": "CARDANO",
    "XMR": "Monero",
    "IOT": "IOTA",
    "TRX": "TRON",
    "DASH": "Dash",
    "BNB": "Binance Coin",
    "NEO": "NEO",
    "ETC": "Ethereum  Classic",
    "XEM": "NEM",
    "XTZ": "Tezos",
    "VET": "VeChain",
    "ZEC": "Zcash",
    "OMG": "OmiseGO",
    "BTG": "Bitcoin Gold",
    "BCN": "Bytecoin",
    "MKR": "Maker",
    "LSK": "Lisk",
}