
//coincap API
export const CRYPTO_FETCHING = 'CRYPTO_FETCHING';
export const CRYPTO_FETCH_SUCESS = 'CRYPTO_FETCH_SUCESS';
export const CRYPTO_DATA_FAIL = "CRYPTO_DATA_FAIL";
export const UPDATE_CRYPTO_DATA = 'UPDATE_CRYPTO_DATA';
export const GLOBAL_DATA = "GLOBAL_DATA";
export const COIN_HISTORY = "COIN_HISTORY";
export const COIN_COMPLETE = "COIN_COMPLETE";
export const CRYPTO_FETCHING_HISTORY ="CRYPTO_FETCHING_HISTORY"

//Social Media and News
export const REDDIT_FETCHED = 'REDDIT_FETCHED'
export const REDDIT_FETCHING = 'REDDIT_FETCHING'
export const REDDIT_DATA_FAIL = 'REDDIT_DATA_FAIL'



//Currency Rate
export const CURRENCY_RATE = "CURRENCY_RATE";
export const CURRENCY_ERROR = "CURRENCY_ERROR";
export const CURRENCY_FETCHING = 'CURRENCY_FETCHING';
export const CURRENCY_INR = "CURRENCY_INR"


//News 
export const NEWS_FETCHING_SUCESS = "NEWS_FETCHING_SUCESS";
export const NEWS_FETCHING = "NEWS_FETCHING";
export const NEWS_FETCHING_FAIL = "NEWS_FETCHING_FAIL"
export const COIN_NEWS_STATE = "COIN_NEWS_STATE"



//NavBar 
export const NAVBAR_ACTIVE_STATE = "NAVBAR_ACTIVE_STATE"


//Exchanges 
export const EXCHANGE_CURRENCY_FETCHING = "EXCHANGE_CURRENCY_FETCHING"
export const EXCHANGE_CURRENCY_FETCH_SUCCESS = "EXCHANGE_CURRENCY_FETCH_SUCCESS"
export const EXCHANGE_CURRENCY_FETCH_ERROR = "EXCHANGE_CURRENCY_FETCH_ERROR"