
//coincap API
export const CRYPTO_FETCHING = 'CRYPTO_FETCHING';
export const CRYPTO_FETCH_SUCESS = 'CRYPTO_FETCH_SUCESS';
export const CRYPTO_DATA_FAIL = "CRYPTO_DATA_FAIL";
export const UPDATE_CRYPTO_DATA = 'UPDATE_CRYPTO_DATA';
export const GLOBAL_DATA = "GLOBAL_DATA";
export const COIN_HISTORY = "COIN_HISTORY";
export const COIN_COMPLETE = "COIN_COMPLETE";


//Social Media and News
export const REDDIT_FETCHED = 'REDDIT_FETCHED'
export const REDDIT_FETCHING = 'REDDIT_FETCHING'
export const REDDIT_DATA_FAIL = 'REDDIT_DATA_FAIL'



//Currency Rate
export const CURRENCY_RATE = "CURRENCY_RATE";
export const CURRENCY_ERROR = "CURRENCY_ERROR";
export const CURRENCY_FETCHING = 'CURRENCY_FETCHING';


//NavBar 
// export const NAVBAR_ACTIVE_STATE = "NAVBAR_ACTIVE_STATE"
